[[language]]
name = "c"
file-types = ["c", "h"]
auto-format = true

# python related

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.ty]
command = "ty"
args = ["server"]

[[language]]
name = "python"
language-servers = [
  { name = "ruff", only-features = ["diagnostics", "code-action"] },
  { name = "ty", except-features = ["format"] },
]
auto-format = true
formatter = { command = "ruff", args = ["format", "-"] }

# nix
[[language]]
name = "nix"
language-servers = [ "nixd" ]

[language-server.nixd]
command = "nixd"
args = ["--semantic-tokens=true"]

[language-server.nixd.config.nixd.formatting]
command = ["nixfmt"]

[language-server.nixd.config.nixd.nixpkgs]
# Point to your local nixpkgs channel or flake inputs
expr = "import (builtins.getFlake (toString github:mindnbytes/nixos-dotfiles)).inputs.nixpkgs { }"

[language-server.nixd.config.nixd.options.home-manager]
expr = "(builtins.getFlake (toString github:mindnbytes/nixos-dotfiles)).homeConfigurations.alex-macbook.options"


[language-server.nixd.config.nixd.options.nixos]
expr = "(builtins.getFlake (toString github:mindnbytes/nixos-dotfiles)).nixosConfigurations.nixos-btw.options"
